site_name: pylts Docs
site_description: Pydantic wrapper around litestreamed database specific to an AWS bucket.
site_url: https://mv3.dev
site_author: Marcelino Veloso III
repo_url: https://github.com/justmars/pylts
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: index.md
  - Litestream AWS API: api.md
  - CLI sample: cli.md
  - Dockerfile Sample: docker.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/justmars
      name: justmars on Github
    - icon: fontawesome/brands/mastodon
      link: https://esq.social/@mv
      name: mv on Mastodon
copyright: Copyright &copy; Marcelino Veloso III

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_category_heading: true
            show_source: true
            heading_level: 4
  - search:
      lang: en
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
